"use client";

import Link from "next/link";
import { StatusBanner } from "../../../components/ui/StatusBanner";
import { ExpensesTab } from "./components/ExpensesTab";
import { ExplainTab } from "./components/ExplainTab";
import { GroupTabNav } from "./components/GroupTabNav";
import { HistoryTab } from "./components/HistoryTab";
import { MembersTab } from "./components/MembersTab";
import { SettleTab } from "./components/SettleTab";
import { useGroupPageController } from "./useGroupPageController";

export default function GroupPage() {
  const {
    groupName,
    groupId,
    groupError,
    loadGroup,
    tabs,
    activeTab,
    setActiveTab,
    getSectionClass,
    editingGroupName,
    savingGroupName,
    renameGroupError,
    userName,
    addingMember,
    addMemberError,
    loadingMembers,
    membersError,
    members,
    setEditingGroupName,
    saveGroupName,
    setUserName,
    addMember,
    getMemberName,
    editingExpenseId,
    desc,
    amount,
    paidByUserId,
    splitMode,
    exactAmounts,
    percentages,
    shares,
    addingExpense,
    addExpenseError,
    expenses,
    expensesSort,
    expensesPage,
    expensesPageSize,
    expensesTotalPages,
    expensesTotalItems,
    loadingExpenses,
    expensesError,
    deletingExpenseId,
    deleteExpenseError,
    editDesc,
    editAmount,
    editPaidByUserId,
    editSplitMode,
    editExactAmounts,
    editPercentages,
    editShares,
    updatingExpense,
    updateExpenseError,
    setDesc,
    setAmount,
    setPaidByUserId,
    setSplitMode,
    setExactAmounts,
    setPercentages,
    setShares,
    addExpense,
    setExpensesSort,
    loadExpenses,
    startEditExpense,
    deleteExpense,
    setExpensesPageSize,
    setEditDesc,
    setEditAmount,
    setEditPaidByUserId,
    updateExpense,
    resetEditExpense,
    setEditSplitMode,
    setEditExactAmounts,
    setEditPercentages,
    setEditShares,
    settlements,
    loadingSettlements,
    settlementsError,
    confirmationId,
    confirmationIdError,
    confirmTransferError,
    paidTransfers,
    confirmingTransfers,
    ledgerEntries,
    loadingLedger,
    ledgerError,
    ledgerExplanationByUserId,
    loadingLedgerExplanation,
    owesFromUserId,
    owesToUserId,
    owesAmount,
    owesHistoricalAmount,
    owesView,
    loadingOwes,
    owesError,
    setConfirmationId,
    generateConfirmationIdFromApi,
    loadSettlements,
    confirmPaidTransfer,
    loadLedger,
    setOwesFromUserId,
    setOwesToUserId,
    loadOwes,
    loadOwesHistorical,
    ledgerExplanationError,
    loadLedgerExplanation,
    currentUserId,
    setCurrentUserId,
    selectedLedgerExplanationUserId,
    setSelectedLedgerExplanationUserId,
    ledgerExplanationEntries,
    formatMoney,
    formatContributionDescription,
    getShortTimeZoneLabel,
    memberNameById,
    confirmedTransfers,
    confirmedTransfersSort,
    confirmedTransfersPage,
    confirmedTransfersPageSize,
    confirmedTransfersTotalPages,
    confirmedTransfersTotalItems,
    loadingConfirmedTransfers,
    confirmedTransfersError,
    confirmedFilter,
    events,
    eventsSort,
    eventsPage,
    eventsPageSize,
    eventsTotalPages,
    eventsTotalItems,
    loadingEvents,
    eventsError,
    setConfirmedTransfersSort,
    loadConfirmedTransfers,
    setConfirmedFilter,
    setConfirmedTransfersPageSize,
    setEventsSort,
    loadEvents,
    setEventsPageSize,
  } = useGroupPageController();
  return (
    <main className="min-h-screen bg-gradient-to-br from-amber-50 via-rose-50 to-orange-50 p-6 text-slate-900">
      <div className="mx-auto flex max-w-3xl flex-col gap-6">
        <Link href="/" className="text-sm font-medium text-slate-600 underline">
          ← Back
        </Link>

        <div className="mt-2">
          <h1 className="text-3xl font-semibold tracking-tight">
            {groupName?.trim()
              ? groupName
              : `Group ${Number.isFinite(groupId) ? `#${groupId}` : ""}`}
          </h1>
        </div>

        {groupError && (
          <StatusBanner
            variant="error"
            message={groupError}
            onRetry={() => Number.isFinite(groupId) && loadGroup(groupId)}
          />
        )}

        <GroupTabNav
          tabs={tabs}
          activeTab={activeTab}
          onTabChange={setActiveTab}
        />

        <MembersTab
          sectionClass={getSectionClass("members")}
          editingGroupName={editingGroupName}
          savingGroupName={savingGroupName}
          renameGroupError={renameGroupError}
          userName={userName}
          addingMember={addingMember}
          groupId={groupId}
          addMemberError={addMemberError}
          loadingMembers={loadingMembers}
          membersError={membersError}
          members={members}
          setEditingGroupName={setEditingGroupName}
          saveGroupName={saveGroupName}
          setUserName={setUserName}
          addMember={addMember}
          reloadGroup={() => Number.isFinite(groupId) && void loadGroup(groupId)}
          getMemberName={getMemberName}
        />

        <ExpensesTab
          sectionClass={getSectionClass("expenses")}
          activeTab={activeTab}
          editingExpenseId={editingExpenseId}
          groupId={groupId}
          members={members}
          getMemberName={getMemberName}
          desc={desc}
          amount={amount}
          paidByUserId={paidByUserId}
          splitMode={splitMode}
          exactAmounts={exactAmounts}
          percentages={percentages}
          shares={shares}
          addingExpense={addingExpense}
          addExpenseError={addExpenseError}
          expenses={expenses}
          expensesSort={expensesSort}
          expensesPage={expensesPage}
          expensesPageSize={expensesPageSize}
          expensesTotalPages={expensesTotalPages}
          expensesTotalItems={expensesTotalItems}
          loadingExpenses={loadingExpenses}
          expensesError={expensesError}
          deletingExpenseId={deletingExpenseId}
          deleteExpenseError={deleteExpenseError}
          editDesc={editDesc}
          editAmount={editAmount}
          editPaidByUserId={editPaidByUserId}
          editSplitMode={editSplitMode}
          editExactAmounts={editExactAmounts}
          editPercentages={editPercentages}
          editShares={editShares}
          updatingExpense={updatingExpense}
          updateExpenseError={updateExpenseError}
          setDesc={setDesc}
          setAmount={setAmount}
          setPaidByUserId={setPaidByUserId}
          setSplitMode={setSplitMode}
          setExactAmounts={setExactAmounts}
          setPercentages={setPercentages}
          setShares={setShares}
          addExpense={addExpense}
          setExpensesSort={setExpensesSort}
          loadExpenses={loadExpenses}
          startEditExpense={startEditExpense}
          deleteExpense={deleteExpense}
          setExpensesPageSize={setExpensesPageSize}
          setEditDesc={setEditDesc}
          setEditAmount={setEditAmount}
          setEditPaidByUserId={setEditPaidByUserId}
          updateExpense={updateExpense}
          resetEditExpense={resetEditExpense}
          setEditSplitMode={setEditSplitMode}
          setEditExactAmounts={setEditExactAmounts}
          setEditPercentages={setEditPercentages}
          setEditShares={setEditShares}
        />

        <SettleTab
          sectionClass={getSectionClass("settle")}
          groupId={groupId}
          members={members}
          settlements={settlements}
          loadingSettlements={loadingSettlements}
          settlementsError={settlementsError}
          confirmationId={confirmationId}
          confirmationIdError={confirmationIdError}
          confirmTransferError={confirmTransferError}
          paidTransfers={paidTransfers}
          confirmingTransfers={confirmingTransfers}
          ledgerEntries={ledgerEntries}
          loadingLedger={loadingLedger}
          ledgerError={ledgerError}
          ledgerExplanationByUserId={ledgerExplanationByUserId}
          loadingLedgerExplanation={loadingLedgerExplanation}
          owesFromUserId={owesFromUserId}
          owesToUserId={owesToUserId}
          owesAmount={owesAmount}
          owesHistoricalAmount={owesHistoricalAmount}
          owesView={owesView}
          loadingOwes={loadingOwes}
          owesError={owesError}
          getMemberName={getMemberName}
          setConfirmationId={setConfirmationId}
          generateConfirmationIdFromApi={generateConfirmationIdFromApi}
          loadSettlements={loadSettlements}
          confirmPaidTransfer={confirmPaidTransfer}
          loadLedger={loadLedger}
          setOwesFromUserId={setOwesFromUserId}
          setOwesToUserId={setOwesToUserId}
          loadOwes={loadOwes}
          loadOwesHistorical={loadOwesHistorical}
        />
        <ExplainTab
          sectionClass={getSectionClass("explain")}
          groupId={groupId}
          loadingLedgerExplanation={loadingLedgerExplanation}
          ledgerExplanationError={ledgerExplanationError}
          loadLedgerExplanation={loadLedgerExplanation}
          currentUserId={currentUserId}
          setCurrentUserId={setCurrentUserId}
          members={members}
          getMemberName={getMemberName}
          selectedLedgerExplanationUserId={selectedLedgerExplanationUserId}
          setSelectedLedgerExplanationUserId={setSelectedLedgerExplanationUserId}
          ledgerExplanationEntries={ledgerExplanationEntries}
          formatMoney={formatMoney}
          formatContributionDescription={formatContributionDescription}
          getShortTimeZoneLabel={getShortTimeZoneLabel}
          memberNameById={memberNameById}
        />

        <HistoryTab
          sectionClass={getSectionClass("history")}
          groupId={groupId}
          members={members}
          getMemberName={getMemberName}
          confirmedTransfers={confirmedTransfers}
          confirmedTransfersSort={confirmedTransfersSort}
          confirmedTransfersPage={confirmedTransfersPage}
          confirmedTransfersPageSize={confirmedTransfersPageSize}
          confirmedTransfersTotalPages={confirmedTransfersTotalPages}
          confirmedTransfersTotalItems={confirmedTransfersTotalItems}
          loadingConfirmedTransfers={loadingConfirmedTransfers}
          confirmedTransfersError={confirmedTransfersError}
          confirmedFilter={confirmedFilter}
          events={events}
          eventsSort={eventsSort}
          eventsPage={eventsPage}
          eventsPageSize={eventsPageSize}
          eventsTotalPages={eventsTotalPages}
          eventsTotalItems={eventsTotalItems}
          loadingEvents={loadingEvents}
          eventsError={eventsError}
          memberNameById={memberNameById}
          setConfirmedTransfersSort={setConfirmedTransfersSort}
          loadConfirmedTransfers={loadConfirmedTransfers}
          setConfirmedFilter={setConfirmedFilter}
          setConfirmedTransfersPageSize={setConfirmedTransfersPageSize}
          setEventsSort={setEventsSort}
          loadEvents={loadEvents}
          setEventsPageSize={setEventsPageSize}
        />
      </div>
    </main>
  );
}
